config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout"}
  root to: 'students#index'
  resources :students
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
	has_many :student_marks

	accepts_nested_attributes_for :student_marks


	def get_total_marks
		self.student_marks.sum(:marks)
	end
end

app/models/student_mark.rb
class StudentMark < ApplicationRecord
	belongs_to :student
	belongs_to :subject
end

app/models/subject.rb
class Subject < ApplicationRecord
	has_many :student_marks
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,:timeoutable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	  include Pagy::Backend

	before_action :authenticate_user!
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
	def index
		# @students = Student.all
		@pagy, @students = pagy(Student.all, items: 10) 

		@subjects = Subject.all
		@student_marks = StudentMark.new
	end

	def new
		@student = Student.new
		@subjects = Subject.all
	end

	def append_data
		# @student = Student.find_by(id: params[:id])
		@subjects = Subject.all

	end

	def create
		@student = Student.new(first_name: params[:student][:first_name], last_name: params[:student][:last_name])
		if @student.save
				update_marks
				notice = "Student created succesfully"
				redirect_to students_path, flash: {notice: notice}
		else
			alert = "Student not created"
			redirect_to students_path,flash: {alert: alert}
		end
	end

	def edit
		@student = Student.find_by(id: params[:id])
	end

	def show
		@student = Student.find_by(id: params[:id])
	end

	def update
		@student = Student.find_by(id: params[:id])
		if @student.update(first_name: params[:student][:first_name], last_name: params[:student][:last_name])
			update_marks
			notice = "Student updated succesfully"
			redirect_to students_path, flash: {notice: notice}
		else
			alert = "Student not updated"
			redirect_to students_path, flash: {alert: alert}
		end
	end

	def update_marks
		if params[:subjects].present?
			params[:subjects].each do |s|
				if s["marks"].present? && s["subject_id"].present?
					student_mark = @student.student_marks.find_by(subject_id: s["subject_id"])
					if student_mark.present?
						student_mark.update!(marks: s["marks"])
					else
						@student.student_marks.create!(subject_id: s["subject_id"], marks: s['marks'])
					end
				end
			end
		end
	end

	def destroy
		@student = Student.find_by(id: params[:id])
		if @student.destroy
			flash[:notice] = "Student deleted"
			redirect_to students_path, flash: {notice: notice}
		else
			flash[:alert] = "Student not deleted"
			redirect_to students_path, flash: {alert: alert}
		end

	end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
	def index
		@subjects = Subject.all
	end

	def create
		@subject = Subject.create(subject_name: params[:subject][:subject_name])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
	include Pagy::Frontend
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/layouts/_header.html.erb
<div class="container">
	<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
	  <a class="navbar-brand" href="#">SCHOOL</a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>
	  <div class="collapse navbar-collapse" id="navbarNav">
	    <ul class="navbar-nav">
	      <li class="nav-item active">
	      	<%= link_to "Students",students_path, class: "nav-link" %>
	      </li>
	      <li class="" style="margin-left: 762px;"><%= link_to 'Sign out', destroy_user_session_path,method: :delete, class: "nav-link " %></li>
	    </ul>
	  </div>
	</nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>School</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/_edit_form.html.erb
<%= form_for(:student,:as => @student, :url => student_path(@student), method: :put ) do |f| %>
  <div class="form-row">
    <div class="col">
      <%= f.hidden_field :id%>
      <%= f.text_field :first_name,id: "f_name", class: "form-control", placeholder: "First Name*"%>
      <span id="f_err" style="color: red"></span>
    </div>
    <div class="col">
      <%= f.text_field :last_name,id: "l_name", class: "form-control", placeholder: "Last Name*"%>
      <span id="l_err" style="color: red"></span>
    </div>
  </div>
  <br>
  <% if @student.student_marks.present? %>
  <% @student.student_marks.each do |s|%>
      <div class="form-row">
        <div class="col">
          <%= select_tag "subjects[][subject_id]", options_for_select(@subjects.collect{ |u| [u.subject_name, u.id]},s.subject_id), class: "form-control"%>
        </div>
        <div class="col">
          <%= text_field_tag "subjects[][marks]", s.marks, class: "form-control", placeholder: "Marks", multiple: true%>
        </div>
    </div>
    <br>
    <% end %>
  <% end %>
  <div id="add_subject_edit_<%=@student.id%>">
    
  </div>
  <br>
  <button id="edit_sub_<%=@student.id%>" class="btn btn-primary">Add</button>
  
  <div class="form-row ">
    <div class="col pull-right">
      <%= f.submit "Save", class: "btn btn-primary update_form"%>
      <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    </div>
  </div>
<% end %>

<script type="text/javascript">
  value = $("#student_id").val()
  sub_val = "#add_subject_edit_"+value
  edit_val = "#edit_sub_"+value
  $(edit_val).on('click',function(){
    $(sub_val).append("<%= escape_javascript("#{render :partial => 'subject_marks'}").html_safe %>")
    return false;
  })

  $(".update_form").on('click',function(){
    var first_name = $("#f_name").val()
    var last_name = $("#l_name").val()
    var first_name_error = (first_name == '' || first_name == undefined || first_name == null)
    var last_name_error = (last_name == '' || last_name == undefined || last_name == null)
    if(first_name_error && last_name_error){
      $("#first_name_err").text("Please enter first name")
      $("#last_name_err").text("Please enter last name")
      return false;
    }
    else if(first_name == '' || first_name == undefined || first_name == null){
      $("#f_err").text("Please enter first name")
      $("#l_err").text("")
      return false;
    }
    else if(last_name == '' || last_name == undefined || last_name == null){
      $("#l_err").text("Please enter last name")
      $("#f_err").text("")
      return false;
    }else{
      $("#f_err").text("")
      $("#l_err").text("")
      return true;
    }
  })
</script>

app/views/students/_form.html.erb
<%= form_for(:student,:as => @student, :url => students_path(@student) ) do |f| %>
  <div class="form-row">
    <div class="col">
      <%= f.text_field :first_name, class: "form-control", placeholder: "First Name*"%>
      <span id="first_name_err" style="color: red"></span>
    </div>
    <div class="col">
      <%= f.text_field :last_name, class: "form-control", placeholder: "Last Name*"%>
      <span id="last_name_err" style="color: red"></span>
    </div>
  </div>
  <br>
  <div>
    <%= render 'subject_marks'%>
  </div>
  <div class="add_subject">
    
  </div>
  <button id="add_sub">Add</button>
  <br>
  <div class="form-row ">
    <div class="col pull-right">
      <%= f.submit "Save", class: "btn btn-primary save_form"%>
      <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    </div>
  </div>
<% end %>

<script type="text/javascript">
  $("#add_sub").on('click',function(){
    console.log("test ")
    $(".add_subject").append("<%= escape_javascript("#{render :partial => 'subject_marks'}").html_safe %>")
    return false;
  })


  $(".save_form").on('click',function(){
    var first_name = $("#student_first_name").val()
    var last_name = $("#student_last_name").val()
    var first_name_error = (first_name == '' || first_name == undefined || first_name == null)
    var last_name_error = (last_name == '' || last_name == undefined || last_name == null)
    if(first_name_error && last_name_error){
      $("#first_name_err").text("Please enter first name")
      $("#last_name_err").text("Please enter last name")
      return false;
    }
    else if(first_name == '' || first_name == undefined || first_name == null){
      $("#first_name_err").text("Please enter first name")
      $("#last_name_err").text("")
      return false;
    }
    else if(last_name == '' || last_name == undefined || last_name == null){
      $("#last_name_err").text("Please enter last name")
      $("#first_name_err").text("")
      return false;
    }else{
      $("#first_name_err").text("")
      $("#last_name_err").text("")
      return true;
    }
  })

</script>

app/views/students/_subject_marks.html.erb
<div class="form-row">
	<div class="col">
	  <%= select_tag "subjects[][subject_id]", options_for_select(@subjects.collect{ |u| [u.subject_name, u.id] }), class: "form-control"%>
	</div>
	<div class="col">
	  <%= text_field_tag "subjects[][marks]", '', class: "form-control", placeholder: "Marks", multiple: true%>
	</div>
</div>
<br>

app/views/students/index.html.erb
<div class="container">
  <%= render './layouts/header'%>
  <div class="container">
    <br>
    <div class="card">
      <div class="card-body">
        <h3 class="card-title" align="center">Student Details

        </h3>
        <!-- <hr> -->
        <% if  @students.present? %>
          <div class="table-responsive">
            <table class="table">
              <thead class="thead-light">
                <tr>
                  <th scope="col">First Name</th>
                  <th scope="col">Last Name</th>
                  <th scope="col">Total Marks</th>
                  <th>
                    <span class="col-sm-2 pull-right">
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#StudentForm">
                      New Student
                    </button>
                    <!-- Modal -->
                    <div class="modal fade" id="StudentForm" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
                      aria-hidden="true">
                      <div class="modal-dialog" role="document">
                        <div class="modal-content">
                          <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Student Form</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                            </button>
                          </div>
                          <div class="modal-body">
                            <%= render 'form', locals: {:student => nil}%>
                          </div>
                        </div>
                      </div>
                    </div>
                  </span>
                  </th>
                </tr>
              </thead>
              <tbody>
                <% @students.each do |student|%>
                  <tr>
                    <td scope="col"><%= student.first_name %></td>
                    <td scope="col"><%= student.last_name %></td>
                    <td scope="col"><%= student.get_total_marks rescue '-' %></td>
                    <td>
                      <%= link_to 'View', student_path(student), class: "btn btn-primary" %>
                      <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#edit_form_<%= student.id %>" value="<%=student.id%>">
                      Edit
                    </button>

                    <div class="modal fade" id="edit_form_<%= student.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                      <div class="modal-dialog" role="document">
                        <div class="modal-content">
                          <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Edit Form</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                            </button>
                          </div>
                          <div class="modal-body">
                            <%@student = student%>
                            
                            <%= render partial: 'edit_form', locals: {:student => @student} %>
                          </div>
                        </div>
                      </div>
                    </div>
                    </div>
                    <%= link_to 'Delete', student , method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-primary"%>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        <% else %>
          <div class="alert alert-primary" role="alert">
            No students to display
          </div>
        <% end %>
      </div>
    </div>
  </div>


<br>
<div class="container">
  <%= pagy_bootstrap_nav(@pagy).html_safe %>
</div>
</div>

app/views/students/show.html.erb
<div class="container">
  <%= render './layouts/header'%>
  <br>
  <div class="container">
  	<div class="card">
  <div class="card-body">
    <h5 class="card-title">Student Details</h5>
    <hr>
    <p class="card-text">First Name : <%= @student.first_name%></p>
    <p class="card-text">Last Name : <%= @student.last_name%></p>
    
    <div class="table-responsive">
      <table class="table table-bordered">
        <thead class="thead-light">
        	<tr>
        		<td colspan="3", align="center"> 
        			<b> Subject Details </b>
        		</td>
        	</tr>
        	<tr>
        		<th>Subject Name</th>	
        		<th>Marks</th>	
        	</tr>
        </thead>
        <tbody>
        	<% @student.student_marks.each do |subject| %>
          	<tr>
          		<td><%= subject.subject.subject_name %></td>	
          		<td><%= subject.marks %></td>	
          	</tr>
        	<% end %>
        </tbody>
      </table>
    </div>

  </div>
</div>
  </div>
</div>